apiVersion: apps/v1
kind: Deployment
metadata:
  name: scripts
  labels:
    app: scripts
spec:
  replicas: 5
  selector:
    matchLabels:
      app: scripts
  template:
    metadata:
      labels:
        app: scripts
    spec:
      containers:
      - name: scripts
        image: gcr.io/mechmania2017/scripts:latest
        ports:
          - containerPort: 3000
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: creds
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: creds
                key: aws_secret_access_key
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /gcr
          name: gcr
          readOnly: true
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: File
      - name: gcr
        secret:
          secretName: gcr
---
apiVersion: v1
kind: Service
metadata:
  name: scripts-service
spec:
  type: LoadBalancer
  selector:
    app: scripts
  ports:
    - port: 80
      name: scripts-service
      targetPort: 3000
      protocol: TCP
